Repository woowa-techcamp-2021/cashbook-1, pull requests merged in 2021-08, with the labels that each got.

#79 [BE] 결제수단 불러오기 API
  api/routes/payment/index.ts
  api/services/payment.ts
  api/utils/jwt.ts
Labels: BE, feature

#80 [BE] 결제내역 추가하기 API
  api/routes/transaction/index.ts
  api/services/payment.ts
  api/services/transaction.ts
  api/utils/errorHandler.ts
Labels: BE, feature

#83 차트 페이지에 필요한 통계 데이터 API
  api/routes/transaction/statistics/index.ts
  api/services/transaction.ts
  api/utils/errorHandler.ts
Labels: BE, feature

#84 [BE] 메인화면 거래내역 조회 API
  api/routes/transaction/index.ts
  api/services/transaction.ts
  api/types/transaction.ts
  api/utils/errorHandler.ts
Labels: BE, feature

#86 [BE] 달력 통계 조회 API 구현
  api/services/transaction.ts
  api/types/transaction.ts
Labels: BE, feature

#87 [BE]fix유저아이디 목데이터 삭제 및 access token 적용
  api/routes/payment/index.ts
  api/routes/transaction/index.ts
Labels: BE, refactoring

#89 로그인 / 회원가입 페이지 API 연동
  client/src/configs/urls.ts
  client/src/pages/SignInPage/index.ts
  client/src/pages/SignInPage/style.scss
  client/src/pages/SignUpPage/index.ts
  client/src/pages/SignUpPage/style.scss
  client/src/utils/checkInputValidity.ts
  client/src/utils/fetchWrapper.ts
  client/src/utils/getValidityMessages.ts
Labels: FE, feature

#90 [FE] 메인화면 거래내역 패치 후 렌더링
  api/services/transaction.ts
  client/src/api/transaction.ts
  client/src/components/Header/index.ts
  client/src/components/Header/style.scss
  client/src/components/TransactionForm/index.ts
  client/src/components/TransactionHeader/index.ts
  client/src/components/TransactionList/DayTransaction.ts
  client/src/components/TransactionList/TransactionRecord.ts
  client/src/components/TransactionList/index.ts
  client/src/store/transaction.ts
  client/src/utils/date.ts
  client/webpack.dev.js
Labels: FE, feature

#91 [FE] 메인화면, 달력 데이터 받아와서 렌더링
  api/configs/cors.ts
  api/services/transaction.ts
  api/types/transaction.ts
  client/src/api/calendar.ts
  client/src/api/transaction.ts
  client/src/components/Calendar/CalendarDate.ts
  client/src/components/Calendar/TotalPriceInfo.ts
  client/src/components/Header/index.ts
  client/src/components/TransactionHeader/index.ts
  client/src/components/TransactionList/index.ts
  client/src/configs/urls.ts
  client/src/store/calendar.ts
  client/src/utils/calendar.ts
  client/src/utils/dataSetting.ts
  client/src/utils/fetchWrapper.ts
  client/webpack.dev.js
Labels: FE, feature

#92 웹앱 초기 로그인 여부 판단
  client/index.ts
  client/src/App.ts
  client/src/configs/urls.ts
  client/src/lib/router/index.ts
  client/src/pages/SignInPage/index.ts
  client/src/pages/SignUpPage/index.ts
  client/src/utils/fetchWrapper.ts
Labels: FE, feature

#93 [FE] 거래내역 생성
  client/public/assets/icon/xBtn.svg
  client/src/App.ts
  client/src/api/payment.ts
  client/src/api/transaction.ts
  client/src/components/TransactionForm/index.ts
  client/src/components/TransactionForm/style.scss
  client/src/components/dropdown/CategoryDropdown.ts
  client/src/components/dropdown/PaymentDropdown.ts
  client/src/components/dropdown/style.scss
  client/src/configs/urls.ts
  client/src/lib/component/index.ts
  client/src/store/payment.ts
  client/src/utils/category.ts
  client/src/utils/dataSetting.ts
  client/src/utils/date.ts
Labels: FE, feature

#94 결제내역 통계 받아오는 데이터 포맷 변경
  api/services/transaction.ts
Labels: BE, feature

#95 차트페이지 API 연동
  client/src/api/chart.ts
  client/src/components/CategoryStatistics/drawPieChart.ts
  client/src/components/CategoryStatistics/index.ts
  client/src/components/Trend/drawCoordinatePlane.ts
  client/src/components/Trend/drawLineChart.ts
  client/src/components/Trend/index.ts
  client/src/pages/ChartPage/drawCoordinatePlane.ts
  client/src/pages/ChartPage/drawPieChart.ts
  client/src/pages/ChartPage/index.ts
  client/src/store/statistics.ts
  client/src/utils/category.ts
  client/src/utils/dataSetting.ts
Labels: FE, feature

#96 [FE] 거래내역 수정, 삭제
  client/src/api/transaction.ts
  client/src/components/TransactionForm/index.ts
  client/src/components/TransactionList/TransactionRecord.ts
  client/src/components/dropdown/style.scss
Labels: FE, feature

#98 [Refactor][BE] 백엔드 API 코드 전체적인 리팩토링
  api/app.ts
  api/middlewares/validate-token.ts
  api/models/db.ts
  api/models/init-mock-data.ts
  api/models/schema.ts
  api/package-lock.json
  api/package.json
  api/routes/auth/index.ts
  api/routes/auth/signin/index.ts
  api/routes/auth/signout/index.ts
  api/routes/auth/signup/index.ts
  api/routes/payment/index.ts
  api/routes/transaction/index.ts
  api/routes/transaction/statistics/index.ts
  api/services/auth.ts
  api/services/payment.ts
  api/services/transaction-statistics.ts
  api/services/transaction.ts
  api/types/auth.ts
  api/types/common.ts
  api/types/index.ts
  api/types/statistics.ts
  api/types/transaction.ts
  api/utils/date.ts
  api/utils/error-generator.ts
  api/utils/error-handler.ts
  api/utils/jwt.ts
  client/src/App.ts
Labels: BE, refactoring

#100 [Fix][FE] api 반환값 변화에 따라서 수정
  client/src/components/CategoryStatistics/index.ts
  client/src/components/TransactionForm/index.ts
  client/src/pages/ChartPage/index.ts
  client/src/utils/dataSetting.ts
Labels: FE, refactoring

#101 [FE,BE] 거래내역 추가, 수정 에러처리
  api/services/transaction.ts
  api/utils/date.ts
  api/utils/error-handler.ts
  api/utils/handleError.ts
  client/src/components/TransactionForm/index.ts
  client/src/components/TransactionForm/style.scss
  client/src/utils/date.ts
Labels: BE, FE, feature

#102 refactor: 토큰 재발행 방식 수정(#97)
  api/.mock.env
  api/middlewares/validate-token.ts
  api/routes/auth/index.ts
  api/routes/payment/index.ts
  api/routes/transaction/index.ts
  api/routes/transaction/statistics/index.ts
  api/services/auth.ts
  api/utils/error-handler.ts
  api/utils/jwt.ts
Labels: BE, refactoring

#103 [FE] 리팩토링
  api/utils/handleError.ts
  client/index.ts
  client/package-lock.json
  client/package.json
  client/src/App.ts
  client/src/api/calendar.ts
  client/src/api/chart.ts
  client/src/api/payment.ts
  client/src/api/transaction.ts
  client/src/components/Calendar/CalendarDate.ts
  client/src/components/Calendar/TotalPriceInfo.ts
  client/src/components/Calendar/index.ts
  client/src/components/CategoryBadge/index.ts
  client/src/components/CategoryStatistics/index.ts
  client/src/components/Header/index.ts
  client/src/components/TransactionForm/index.ts
  client/src/components/TransactionHeader/index.ts
  client/src/components/TransactionList/DayTransaction.ts
  client/src/components/TransactionList/TransactionRecord.ts
  client/src/components/TransactionList/index.ts
  client/src/components/Trend/drawLineChart.ts
  client/src/components/Trend/index.ts
  client/src/components/dropdown/CategoryDropdown.ts
  client/src/components/dropdown/PaymentDropdown.ts
  client/src/constant/category.ts
  client/src/constant/index.ts
  client/src/lib/component/index.ts
  client/src/lib/observer/index.ts
  client/src/lib/observer/type.ts
  client/src/lib/router/index.ts
  client/src/pages/ChartPage/index.ts
  client/src/pages/MainPage/index.ts
  client/src/pages/SignInPage/index.ts
  client/src/pages/SignUpPage/index.ts
  client/src/store/calendar.ts
  client/src/store/page.ts
  client/src/store/payment.ts
  client/src/store/statistics.ts
  client/src/store/transaction.ts
  client/src/type/category.ts
  client/src/type/statistics.ts
  client/src/type/transaction.ts
  client/src/utils/calendar.ts
  client/src/utils/category.ts
  client/src/utils/dataSetting.ts
  client/src/utils/date.ts
  client/src/utils/dom.ts
Labels: FE, refactoring

#106 [FE] 리팩토링
  client/index.ts
  client/src/components/CategoryStatistics/index.ts
  client/src/components/Header/index.ts
  client/src/components/TransactionHeader/index.ts
  client/src/components/TransactionList/TransactionRecord.ts
  client/src/components/dropdown/PaymentDropdown.ts
  client/src/pages/SignInPage/index.ts
  client/src/pages/SignUpPage/index.ts
  client/src/utils/dataSetting.ts
Labels: FE, refactoring

#108 [FE] 결제수단 추가,삭제 구현
  client/src/api/calendar.ts
  client/src/api/chart.ts
  client/src/api/index.ts
  client/src/api/payment.ts
  client/src/api/transaction.ts
  client/src/components/TransactionForm/index.ts
  client/src/components/TransactionList/TransactionRecord.ts
  client/src/components/dropdown/PaymentDropdown.ts
  client/src/components/popup/PaymentAddPopup.ts
  client/src/components/popup/style.scss
  client/src/type/type.ts
Labels: FE, bug, feature

#107 refactor: 토큰 재발행 로직 리팩토링(#24)
  api/middlewares/validate-token.ts
  api/routes/auth/index.ts
  api/routes/payment/index.ts
  api/routes/transaction/index.ts
  api/routes/transaction/statistics/index.ts
  api/services/auth.ts
  api/utils/jwt.ts
  client/index.ts
  client/src/utils/fetchWrapper.ts
Labels: BE, refactoring

#111 깃허브 소셜로그인 구현
  api/package-lock.json
  api/package.json
  api/routes/auth/github/index.ts
  api/routes/auth/index.ts
  api/services/auth.ts
  client/src/api/auth.ts
  client/src/pages/SignInPage/index.ts
  client/src/utils/window.ts
Labels: BE, FE, feature

#109 차트 페이지 리팩토링
  api/routes/transaction/index.ts
  api/services/transaction.ts
  api/types/transaction.ts
  client/src/api/chart.ts
  client/src/components/CategoryStatistics/drawPieChart.ts
  client/src/components/CategoryStatistics/index.ts
  client/src/components/Trend/index.ts
  client/src/pages/ChartPage/index.ts
Labels: BE, FE, feature, refactoring

#115 API 요청이 보내지지 않는 문제 해결
  api/.mock.env
  api/app.ts
  api/configs/cors.ts
  client/src/utils/dataSetting.ts
Labels: BE, FE, refactoring

#119 [FIX] QA기반 오류 수정 및 리팩토링
  client/src/components/Calendar/style.scss
  client/src/components/CategoryStatistics/drawPieChart.ts
  client/src/components/Header/index.ts
  client/src/components/Header/style.scss
  client/src/components/TransactionForm/index.ts
  client/src/components/TransactionForm/style.scss
  client/src/components/TransactionList/DayTransaction.ts
  client/src/components/TransactionList/TransactionRecord.ts
  client/src/components/TransactionList/index.ts
  client/src/components/TransactionList/style.scss
  client/src/components/Trend/index.ts
  client/src/components/popup/style.scss
  client/src/configs/routes.ts
  client/src/pages/LoginProcessPage/index.ts
  client/src/pages/LoginProcessPage/style.scss
  client/src/pages/MainPage/index.ts
  client/src/pages/SignInPage/index.ts
  client/src/utils/dataSetting.ts
Labels: FE, bug

#122 결제수단 삭제 모달 및 추가 기능
  api/services/transaction.ts
  client/public/assets/icon/logoutIcon.svg
  client/src/api/auth.ts
  client/src/components/Header/index.ts
  client/src/components/TransactionForm/index.ts
  client/src/components/dropdown/CategoryDropdown.ts
  client/src/components/dropdown/PaymentDropdown.ts
  client/src/components/dropdown/style.scss
  client/src/components/popup/PaymentDeletePopup.ts
  client/src/components/popup/style.scss
  client/src/constant/category.ts
Labels: feature, FE

#121 UI 버그 수정 및 리팩토링
  client/public/assets/icon/point.svg
  client/src/components/CategoryStatistics/drawPieChart.ts
  client/src/components/CategoryStatistics/index.ts
  client/src/components/Trend/drawCoordinatePlane.ts
  client/src/components/Trend/drawLineChart.ts
  client/src/components/Trend/index.ts
  client/src/pages/ChartPage/index.ts
  client/src/store/statistics.ts
Labels: bug, FE, refactoring
