Repository woowa-techcamp-2021/cashbook-1, pull requests merged in 2021-07, with the labels that each got.

#37 바벨 웹팩 설정
  .gitignore
  client/babel.config.json
  client/index.js
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/webpack.common.js
  client/webpack.dev.js
  client/webpack.prod.js
Labels: FE, setting

#38 프론트엔드 타입스크립트 설정
  client/babel.config.json
  client/index.js
  client/index.scss
  client/index.ts
  client/package-lock.json
  client/package.json
  client/tsconfig.json
  client/webpack.common.js
Labels: FE, setting

#39 [FE] 프론트엔드 폴더구조 셋
  client/.mock.env
  client/src/api/index.ts
  client/src/components/Header/index.ts
  client/src/components/Header/style.scss
  client/src/constant/index.ts
  client/src/lib/component/index.ts
  client/src/lib/observer/index.ts
  client/src/lib/router/index.ts
  client/src/pages/MainPage.ts
  client/src/style/index.scss
  client/src/utils/index.ts
Labels: FE, setting

#40 프론트엔드 eslint, prettier 설정
  client/.eslintrc.json
  client/.prettierrc.json
  client/package-lock.json
  client/package.json
  client/tsconfig.json
  client/webpack.common.js
Labels: FE, setting

#41 express 설정
  .gitignore
  api/app.ts
  api/package-lock.json
  api/package.json
  api/tsconfig.json
Labels: BE, setting

#42 백엔드 디렉토리 구조 설정
  api/middlewares/index.ts
  api/models/index.ts
  api/routes/index.ts
  api/services/index.ts
  api/types/index.ts
Labels: BE, setting

#44 [FE] 컴포넌트 프레임워크, 옵저버 패턴 구현
  client/package.json
  client/src/lib/component/index.ts
  client/src/lib/component/type.ts
  client/src/lib/observer/index.ts
  client/src/lib/observer/type.ts
Labels: FE, feature

#47 백엔드 환경변수 적용
  api/.mock.env
  api/app.ts
  api/utils/env.ts
Labels: BE, setting

#48 Sequelize 추가
  .gitignore
  api/.mock.env
  api/models/db.ts
  api/models/index.ts
  api/package-lock.json
  api/package.json
  api/utils/env.ts
Labels: BE, setting

#50 [FE] 라우터 적용 및 APP 컴포넌트 개발
  client/index.ts
  client/src/App.ts
  client/src/configs/routes.ts
  client/src/lib/component/index.ts
  client/src/lib/router/index.ts
Labels: FE, feature

#53 라우터를 위한 page 전역 상태 추가
  client/src/store/page.ts
Labels: FE, feature

#54 프론트엔드 베이스 코드 추가
  client/.eslintrc.json
  client/index.scss
  client/index.ts
  client/public/assets/icon/calendarIcon.svg
  client/public/assets/icon/chartIcon.svg
  client/public/assets/icon/checkIcon.svg
  client/public/assets/icon/downArrow.svg
  client/public/assets/icon/historyIcon.svg
  client/public/assets/icon/leftArrow.svg
  client/public/assets/icon/picker.svg
  client/public/assets/icon/rightArrow.svg
  client/src/App.ts
  client/src/api/index.ts
  client/src/components/Header/index.ts
  client/src/components/Header/style.scss
  client/src/configs/routes.ts
  client/src/constant/index.ts
  client/src/lib/component/index.ts
  client/src/lib/component/type.ts
  client/src/pages/CalendarPage/index.ts
  client/src/pages/ChartPage/index.ts
  client/src/pages/MainPage.ts
  client/src/pages/MainPage/index.ts
  client/src/style/global.scss
  client/src/style/index.scss
  client/src/style/reset.scss
  client/src/style/variable.scss
  client/src/utils/dom.ts
  client/src/utils/index.ts
  client/tsconfig.json
Labels: FE, feature, markup

#55 로그인, 회원가입 페이지 마크업
  client/public/assets/icon/github.svg
  client/src/configs/routes.ts
  client/src/pages/SignInPage/index.ts
  client/src/pages/SignInPage/style.scss
  client/src/pages/SignUpPage/index.ts
  client/src/pages/SignUpPage/style.scss
Labels: FE, markup

#56 [FE] 메인페이지 마크업
  client/custom.d.ts
  client/public/assets/icon/activeSubmitBtn.svg
  client/public/assets/icon/checkIcon.svg
  client/public/assets/icon/inActiveSubmitBtn.svg
  client/public/assets/icon/plusIcon.svg
  client/public/assets/icon/trashIcon.svg
  client/src/components/CategoryBadge/index.ts
  client/src/components/CategoryBadge/style.scss
  client/src/components/TransactionForm/index.ts
  client/src/components/TransactionForm/style.scss
  client/src/components/TransactionList/DayTransaction.ts
  client/src/components/TransactionList/TransactionRecord.ts
  client/src/components/TransactionList/index.ts
  client/src/components/TransactionList/style.scss
  client/src/constant/category.ts
  client/src/lib/component/index.ts
  client/src/lib/component/type.ts
  client/src/pages/MainPage/index.ts
  client/src/style/reset.scss
  client/src/type/transaction.ts
  client/src/type/type.ts
  client/src/utils/date.ts
  client/src/utils/price.ts
Labels: FE, markup

#57 차트 페이지 마크업
  client/index.scss
  client/src/pages/ChartPage/drawCoordinatePlane.ts
  client/src/pages/ChartPage/drawPieChart.ts
  client/src/pages/ChartPage/index.ts
  client/src/pages/ChartPage/style.scss
Labels: FE, markup

#58 [FE] 메인페이지 거래내역 편집 마크업
  client/src/components/TransactionList/DayTransaction.ts
  client/src/components/TransactionList/TransactionRecord.ts
  client/src/components/TransactionList/style.scss
  client/src/type/transaction.ts
Labels: FE, markup

#61 캔버스 그리기 함수 타입 수정
  client/src/pages/ChartPage/drawCoordinatePlane.ts
  client/src/pages/ChartPage/drawPieChart.ts
Labels: FE

#60 웹서버 추가
  .gitignore
  client/package.json
  server/app.js
  server/bin/www
  server/package-lock.json
  server/package.json
Labels: BE, setting

#62 ERD 생성 후 추출한 DDL
  api/models/ddl.sql
Labels: BE, setting

#64 [FE] 달력 페이지 마크업
  client/src/components/Calendar/CalendarDate.ts
  client/src/components/Calendar/CalendarDay.ts
  client/src/components/Calendar/TotalPriceInfo.ts
  client/src/components/Calendar/index.ts
  client/src/components/Calendar/style.scss
  client/src/pages/CalendarPage/index.ts
  client/src/store/transaction.ts
  client/src/style/global.scss
  client/src/utils/calendar.ts
Labels: FE, markup

#63 [FE] 메인페이지 마크업
  client/public/assets/icon/activePicker.svg
  client/public/assets/icon/inActivePicker.svg
  client/public/assets/icon/picker.svg
  client/src/components/TransactionHeader/index.ts
  client/src/components/TransactionHeader/style.scss
  client/src/pages/MainPage/index.ts
  client/webpack.dev.js
Labels: FE, markup

#65 [FE] 로그인에 따른 routes 설정 및 데모 로그인
  client/index.ts
  client/src/App.ts
  client/src/lib/router/index.ts
  client/src/pages/SignInPage/index.ts
  client/src/store/page.ts
Labels: FE, feature

#67 [API] api 기본코드 추가
  api/app.ts
  api/configs/constants.ts
  api/configs/cors.ts
  api/middlewares/index.ts
  api/middlewares/validateToken.ts
  api/models/init-mock-data.ts
  api/models/schema.ts
  api/routes/auth/index.ts
  api/routes/auth/signin/index.ts
  api/routes/auth/signout/index.ts
  api/routes/auth/signup/index.ts
  api/routes/index.ts
  api/routes/payment/index.ts
  api/routes/transaction/index.ts
  api/routes/transaction/statistics/index.ts
  api/services/auth.ts
  api/services/index.ts
  api/tsconfig.json
  api/utils/errorGenerator.ts
  api/utils/errorHandler.ts
  api/utils/jwt.ts
Labels: BE, setting

#68 API 서버 베이스 코드 수정
  api/.eslintrc.json
  api/.mock.env
  api/models/db.ts
  api/models/schema.ts
  api/package-lock.json
  api/package.json
  api/utils/errorGenerator.ts
  api/utils/errorHandler.ts
  api/utils/hashPassword.ts
  api/utils/jwt.ts
Labels: BE, feature, setting

#70 로그인 API
  api/routes/auth/signin/index.ts
  api/services/auth.ts
  api/utils/errorGenerator.ts
  api/utils/errorHandler.ts
Labels: BE, feature

#71 로그아웃 API
  api/routes/auth/signout/index.ts
Labels: BE, feature

#72 토큰 유효성 검사 API
  api/routes/auth/index.ts
  api/services/auth.ts
  api/utils/jwt.ts
Labels: BE, feature

#74 [BE] 결재수단 생성 API
  api/routes/index.ts
  api/routes/payment/index.ts
  api/services/auth.ts
  api/services/payment.ts
  api/utils/errorHandler.ts
  api/utils/jwt.ts
Labels: BE, feature

#77 [BE] 거래수단 삭제 API
  api/routes/payment/index.ts
  api/services/payment.ts
  api/utils/errorHandler.ts
Labels: BE, feature

#76 토큰 유효성 검사 미들웨어
  api/middlewares/validateToken.ts
  api/utils/errorHandler.ts
  api/utils/jwt.ts
Labels: BE, feature
